config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get "books" => "books#index"
  get "books/:id" => "books#show"
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book
  include ActiveModel::Model

  attr_accessor :id, :title, :description, :author, :image_url, :rating, :ratings_count
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :lists

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  allow_browser versions: :modern

  before_action :set_user_lists

  private

  def set_user_lists
    @lists = Current.user.lists if authenticated?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  allow_unauthenticated_access

  def index
    @books = HardcoverApiService.query_books(params[:query])
  rescue HardcoverApiService::ApiError => error
    @books = []
    flash[:alert] = error.message
  end

  def show
    @book = HardcoverApiService.find_book(params[:id])
  rescue HardcoverApiService::ApiError => error
    flash[:alert] = error.message
    redirect_to root_path
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  def index
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list, notice: "List was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy!
    redirect_to lists_path, status: :see_other, notice: "List was successfully destroyed."
  end

  private

  def set_list
    @list = List.find(params.expect(:id))
  end

  def list_params
    params.expect(list: [ :name ]).merge({ user: Current.user })
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      flash[:success] = "Successfully logged in"
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    flash[:success] = "Successfully logged out"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/index.html.erb
<div class="flex flex-col mb-4">
    <% if flash[:alert] %>
        <div class="flex w-2xl rounded-md bg-red-400 p-4 mb-4">
            <svg class="fill-white size-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12ZM12 8.25a.75.75 0 0 1 .75.75v3.75a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75Zm0 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z" clip-rule="evenodd" />
            </svg>
            <span class="ml-2 text-white"><%= flash[:alert] %></span>
        </div>
    <% end %>

    <% if flash[:success] %>
        <div class="flex w-2xl rounded-md bg-emerald-500 p-4 mb-4">
            <svg class="fill-white size-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12Zm13.36-1.814a.75.75 0 1 0-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 0 0-1.06 1.06l2.25 2.25a.75.75 0 0 0 1.14-.094l3.75-5.25Z" clip-rule="evenodd" />
            </svg>
            <span class="ml-2 text-white"><%= flash[:success] %></span>
        </div>
    <% end %>

    <h1 class="text-4xl font-bold text-center bg-linear-to-r from-indigo-500 to-cyan-500 bg-clip-text text-transparent">Find any book</h1>

    <%= form_with url: root_path, method: :get, class: "relative" do |form| %>
        <%= form.search_field :query, placeholder: "Search...", class: "rounded-2xl border border-gray-300 dark:border-gray-900 dark:bg-gray-900 dark:text-gray-100 shadow-xs w-2xl h-16 p-4 pr-10 outline-0 mt-6" %>
        <%= form.button name: nil, class: "group size-8 bg-linear-to-r from-indigo-500 to-cyan-500 hover:from-indigo-600 hover:to-cyan-600 rounded-3xl flex justify-center items-center absolute right-1 bottom-1 transition duration-300" do %>
            <svg class="size-4 stroke-white group-hover:stroke-gray-100 dark:stroke-gray-900 dark:group-hover:stroke-black stroke-3 transition duration-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 10.5 12 3m0 0 7.5 7.5M12 3v18" />
            </svg>
        <% end %>
    <% end %>

    <% @books.each do |book| %>
        <div class="rounded-2xl border border-gray-200 dark:border-gray-900 dark:bg-gray-900 flex justify-between mt-4 w-2xl">
            <div class="flex">
                <div class="w-16 h-24 m-2 rounded-xl overflow-hidden shadow-xs shadow-gray-500 hover:ring-2 ring-indigo-500">
                    <%= link_to controller: "books", action: "show", id: book.id do %>
                        <% if book.image_url %>
                            <%= image_tag book.image_url, class: "w-16 h-24 object-cover" %>
                        <% else %>
                            <div class="w-16 h-24 bg-gray-500"></div>
                        <% end %>
                    <% end %>
                </div>

                <div class="flex flex-col justify-center w-lg ml-4 py-4">
                    <%= link_to controller: "books", action: "show", id: book.id do %>
                        <h2 class="text-2xl text-gray-600 dark:text-gray-200 font-medium hover:underline underline-offset-1 truncate"><%= book.title %></h2>
                    <% end %>
                    <p class="text-gray-500 dark:text-gray-400 font-light"><%= book.author %></p>
                    <div class="flex mt-1">
                        <svg class="size-5 fill-amber-300 stroke-gray-600 dark:stroke-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                            <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z" clip-rule="evenodd" />
                        </svg>
                        <span class="text-gray-600 dark:text-gray-300 font-light text-sm pl-1"><%= book.rating.round(2) %></span>
                        <span class="text-gray-400 dark:text-gray-500 font-light text-sm pl-1">(<%= book.ratings_count %>)</span>
                    </div>
                </div>
            </div>

            <%= button_to "", class: "group size-10 rounded-3xl border-2 border-indigo-500 hover:bg-indigo-500 flex justify-center items-center mr-2 mt-2 transition duration-300" do %>
                <svg class="stroke-indigo-500 group-hover:stroke-white dark:group-hover:stroke-black size-6 transition duration-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
            <% end %>
        </div>
    <% end %>
</div>

app/views/books/show.html.erb
<div class="flex w-4xl">
    <%= image_tag @book.image_url, class: "h-96 rounded-sm border-1 border-gray-400 dark:border-gray-600" %>
    <div class="flex flex-col ml-4">
        <h1 class="text-4xl text-gray-600 dark:text-gray-200 font-medium"><%= @book.title %></h1>
        <p class="text-gray-500 dark:text-gray-400 font-light mt-2"><%= @book.author %></p>
        <p class="text-xs text-gray-400 dark:text-gray-200 mt-2"><%= @book.description %></p>
        <div class="flex mt-2">
            <svg class="size-5 fill-amber-300 stroke-gray-600 dark:stroke-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z" clip-rule="evenodd" />
            </svg>
            <span class="text-gray-600 dark:text-gray-300 font-light text-sm pl-1"><%= @book.rating.round(2) %></span>
            <span class="text-gray-400 dark:text-gray-400 font-light text-sm pl-1">(<%= @book.ratings_count %>)</span>
        </div>
        <%= button_to "", class: "mt-2 group bg-indigo-500 hover:bg-indigo-600 border-indigo-300 dark:border-indigo-800 border-1 rounded-md overflow-hidden transition duration-300" do %>
            <div class="w-full h-full border-b-4 border-t-1 border-b-indigo-700 hover:border-b-indigo-800 border-t-indigo-200 hover:border-t-indigo-300 flex justify-center items-center transition duration-300">
                <svg class="stroke-white size-6 group-hover:stroke-gray-100 transition duration-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
                <span class="py-4 pr-4 text-white group-hover:text-gray-100">Add to list</span>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="flex justify-between items-center">
    <div class="flex my-2 ml-4">
        <% if authenticated? %>
            <button data-action="sidebar#toggle" class="mr-2 p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-900 transition duration-300">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 dark:stroke-white">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>
            </button>
        <% end %>
        <%= link_to "Books", root_path, class: "p-2 rounded-md text-xl dark:text-white hover:bg-gray-100 dark:hover:bg-gray-900 transition duration-300" %>
    </div>
    <div class="flex items-center mr-4 my-2">
        <button data-controller="dark-mode" data-action="dark-mode#toggle" class="group w-20 bg-indigo-500 hover:bg-indigo-600 border-indigo-300 dark:border-indigo-800 border-1 rounded-md overflow-hidden active:translate-y-1 transition duration-300 active:transition-none">
            <div class="w-full h-full p-2 border-b-4 border-t-1 border-b-indigo-700 hover:border-b-indigo-800 border-t-indigo-200 hover:border-t-indigo-300 flex justify-center items-center transition duration-300">
                <svg class="stroke-amber-300 dark:stroke-white fill-amber-300 dark:fill-indigo-500 dark:group-hover:fill-indigo-600 size-6 transition duration-300" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M12 .75a8.25 8.25 0 0 0-4.135 15.39c.686.398 1.115 1.008 1.134 1.623a.75.75 0 0 0 .577.706c.352.083.71.148 1.074.195.323.041.6-.218.6-.544v-4.661a6.714 6.714 0 0 1-.937-.171.75.75 0 1 1 .374-1.453 5.261 5.261 0 0 0 2.626 0 .75.75 0 1 1 .374 1.452 6.712 6.712 0 0 1-.937.172v4.66c0 .327.277.586.6.545.364-.047.722-.112 1.074-.195a.75.75 0 0 0 .577-.706c.02-.615.448-1.225 1.134-1.623A8.25 8.25 0 0 0 12 .75Z" />
                    <path fill-rule="evenodd" d="M9.013 19.9a.75.75 0 0 1 .877-.597 11.319 11.319 0 0 0 4.22 0 .75.75 0 1 1 .28 1.473 12.819 12.819 0 0 1-4.78 0 .75.75 0 0 1-.597-.876ZM9.754 22.344a.75.75 0 0 1 .824-.668 13.682 13.682 0 0 0 2.844 0 .75.75 0 1 1 .156 1.492 15.156 15.156 0 0 1-3.156 0 .75.75 0 0 1-.668-.824Z" clip-rule="evenodd" />
                </svg>
            </div>
        </button>
        <% if authenticated? %>
            <%= button_to "Logout", session_path, method: :delete, class: "bg-indigo-500 ml-4 py-2 px-4 rounded-md text-center text-white hover:bg-indigo-600 duration-300" %>
        <% else %>
            <%= link_to "Login", new_session_path, class: "bg-indigo-500 ml-4 py-2 px-4 rounded-md text-center text-white hover:bg-indigo-600 duration-300" %>
        <% end %>
    </div>
</div>

app/views/layouts/_sidebar.html.erb
<div data-sidebar-target="sidebar" class="p-6 h-full overflow-y-auto bg-gray-50 dark:bg-gray-900 border-r-1 border-gray-200 dark:border-gray-700 w-64 transition-transform duration-300 delay-200 transform -translate-x-full">
    <h2 class="uppercase text-sm text-gray-600 dark:text-gray-300 mb-4">My lists</h2>
    <% if authenticated? %>
        <ul class="dark:text-white">
            <%= turbo_frame_tag "lists" do %>
                <%= render @lists %>
            <% end %>
        </ul>
        <%= turbo_frame_tag List.new %>
        <%= link_to new_list_path, data: { turbo_frame: dom_id(List.new) }, class: "flex items-center rounded-md bg-indigo-500 hover:bg-indigo-600 duration-300 mt-4" do %>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6 fill-white mx-2">
                <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 9a.75.75 0 0 0-1.5 0v2.25H9a.75.75 0 0 0 0 1.5h2.25V15a.75.75 0 0 0 1.5 0v-2.25H15a.75.75 0 0 0 0-1.5h-2.25V9Z" clip-rule="evenodd" />
            </svg>
            <span class="text-white py-2">New list</span>
        <% end %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Books" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="dark:bg-gray-800 h-screen">
    <main data-controller="sidebar" class="flex h-full">
      <%= render "layouts/sidebar" %>
      <div data-sidebar-target="main" class="overflow-y-auto flex-1 -ml-64 duration-300 delay-200">
        <%= render "layouts/navbar" %>
        <div class="container mx-auto mt-28 px-5 flex justify-center">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, class: "contents") do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul class="list-disc ml-6">
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-4">
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": list.errors[:name].none?, "border-red-400 focus:outline-red-600": list.errors[:name].any?}] %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<li>
  <%= link_to list.name, list, data: { turbo: false }, class: "block text-gray-800 dark:text-gray-200 my-1 p-2 w-52 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 duration-300 truncate" %>
</li>

app/views/lists/create.turbo_stream.erb
<%= turbo_stream.append "lists", @list %>
<%= turbo_stream.update List.new, "" %>

app/views/lists/edit.html.erb
<% content_for :title, "Editing list" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing list</h1>

  <%= render "form", list: @list %>

  <%= link_to "Show this list", @list, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to lists", lists_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/lists/index.html.erb
<% content_for :title, "Lists" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lists</h1>
    <%= link_to "New list", new_list_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="lists" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @lists.any? %>
      <% @lists.each do |list| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render list %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", list, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_list_path(list), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", list, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No lists found.</p>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<% content_for :title, "New list" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New list</h1>

  <%= turbo_frame_tag @list do %>
    <%= render "form", list: @list %>
  <% end %>
</div>

app/views/lists/show.html.erb
<% content_for :title, "Showing list" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing list</h1>

  <%= render @list %>

  <%= link_to "Edit this list", edit_list_path(@list), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this list", @list, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>